version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - spring.application.name=digital_clothing_shop
      - spring.datasource.url=jdbc:postgresql://db:5432/clothing_store
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - app.jwt.expirationMs=3600000

    ports:
      - "8080:8080"
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database_init:/docker-entrypoint-initdb.d
